version: '3.9'

services:
  nginx:
    image: nginx:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./cert:/root/cert
    command: [nginx-debug, '-g', 'daemon off;']

  
  flask:
    image: golang
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./getip.py:/getip.py:ro
      - ./start.sh:/start.sh:ro
      - ./go_web:/go_web:rw
    command: bash /start.sh
    env_file:
      - ./.env

  xui:
    image: enwaiax/x-ui
    container_name: x-ui
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
