version: '3.9'

services:
  nginx:
    image: nginx:latest
    network_mode: host
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
  
  flask:
    image: python
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./getip.py:/getip.py:ro
      - ./start.sh:/start.sh:ro
    command: bash /start.sh


